# 服务端口
server:
  port: 8088

# 微信开放平台
wxPay:
  # appid
#  appid: wx18a58974bcdaae21
  # 商户号
#  partner: 1564369251
  # 商户key
#  partnerkey: TianJinhexingongzhengchu88216470
  # 回调地址
#  notifyurl: http://9x4ch3.natappfree.cc/wx/callback/notify


# freemarker页面静态化
spring:
  freemarker:
    # 静态页面访问路径
    template-loader-path: classpath:/templates/
    # 关闭缓存，及时刷新，生产环境下修改为 true
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    # 模板文件后缀，默认是.html
    suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
  mvc:
    static-path-pattern: /static/**