# 服务端口
server:
  port: 8080

# 微信
wx:
  open:
    # 微信开放平台 appid
    app_id: wx02d614bb4ae55a29
    # 微信开放平台 appsecret
    app_secret: 32a3b10d6b397f9944b58383d720bc84
    # 微信开放平台 重定向url
    redirect_url: http://index

# 日志
logging:
  level:
    com.demo.wxlogin: debug