# 服务端口
server:
  port: 8081

# 微信
wx:
  open:
    # 微信开放平台 appid
    app_id:
    # 微信开放平台 appsecret
    app_secret:
    # 微信开放平台 重定向url
    redirect_url:

# 日志
logging:
  level:
    com.demo.wxlogin: debug